apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    name: test
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: testlog-deployment
  namespace: test
  labels:
    app: testlog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testlog
  template:
    metadata:
      labels:
        app: testlog
    spec:
      containers:
        - name: testlog
          image: emptyxxx/testlog
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: testlog
  labels:
    app: testlog
  namespace: test
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 30001
  selector:
    app: testlog
